-- ============================================================
-- Seed: Professioni / Settori "In che settore lavori:"
-- Esegui su phpMyAdmin → tab SQL
-- INSERT IGNORE salta righe con slug già esistente
-- ============================================================

INSERT IGNORE INTO `professions` (`name`, `slug`, `description`, `is_active`, `created_at`, `updated_at`) VALUES
('Avvocatura',                           'avvocatura',                          NULL, 1, NOW(), NOW()),
('Commercialista / Consulenza fiscale',  'commercialista-consulenza-fiscale',    NULL, 1, NOW(), NOW()),
('Architettura',                         'architettura',                         NULL, 1, NOW(), NOW()),
('Geometra',                             'geometra',                             NULL, 1, NOW(), NOW()),
('Tipografia / Stampa',                  'tipografia-stampa',                    NULL, 1, NOW(), NOW()),
('Parrucchiere',                         'parrucchiere',                         NULL, 1, NOW(), NOW()),
('Centro estetico',                      'centro-estetico',                      NULL, 1, NOW(), NOW()),
('Fioraio',                              'fioraio',                              NULL, 1, NOW(), NOW()),
('Abbigliamento',                        'abbigliamento',                        NULL, 1, NOW(), NOW()),
('Pasticceria',                          'pasticceria',                          NULL, 1, NOW(), NOW()),
('Ristorazione',                         'ristorazione',                         NULL, 1, NOW(), NOW()),
('Pizzeria',                             'pizzeria',                             NULL, 1, NOW(), NOW()),
('Pub / Bar',                            'pub-bar',                              NULL, 1, NOW(), NOW()),
('Radio / Comunicazione',                'radio-comunicazione',                  NULL, 1, NOW(), NOW()),
('Programmazione / Sviluppo software',   'programmazione-sviluppo-software',     NULL, 1, NOW(), NOW()),
('Grafica / Web design',                 'grafica-web-design',                   NULL, 1, NOW(), NOW()),
('Art direction',                        'art-direction',                        NULL, 1, NOW(), NOW()),
('Telefonia / Elettronica',              'telefonia-elettronica',                NULL, 1, NOW(), NOW()),
('Profumeria',                           'profumeria',                           NULL, 1, NOW(), NOW()),
('Formazione',                           'formazione',                           NULL, 1, NOW(), NOW()),
('Coaching',                             'coaching',                             NULL, 1, NOW(), NOW()),
('Google Specialist / Digital Marketing','google-specialist-digital-marketing',  NULL, 1, NOW(), NOW()),
('Alberghi / B&B',                       'alberghi-bb',                          NULL, 1, NOW(), NOW()),
('Meccanico',                            'meccanico',                            NULL, 1, NOW(), NOW()),
('Carrozzeria',                          'carrozzeria',                          NULL, 1, NOW(), NOW()),
('Elettrauto',                           'elettrauto',                           NULL, 1, NOW(), NOW()),
('Rivendita auto',                       'rivendita-auto',                       NULL, 1, NOW(), NOW()),
('Noleggio auto',                        'noleggio-auto',                        NULL, 1, NOW(), NOW()),
('Autoricambi',                          'autoricambi',                          NULL, 1, NOW(), NOW()),
('Agenzia viaggi',                       'agenzia-viaggi',                       NULL, 1, NOW(), NOW()),
('Farmacia',                             'farmacia',                             NULL, 1, NOW(), NOW()),
('Psicologia',                           'psicologia',                           NULL, 1, NOW(), NOW()),
('Pittura / Decorazione',                'pittura-decorazione',                  NULL, 1, NOW(), NOW()),
('Arredamento',                          'arredamento',                          NULL, 1, NOW(), NOW()),
('Ristrutturazioni / Edilizia',          'ristrutturazioni-edilizia',            NULL, 1, NOW(), NOW()),
('Prodotti chimici',                     'prodotti-chimici',                     NULL, 1, NOW(), NOW()),
('Prodotti tipici',                      'prodotti-tipici',                      NULL, 1, NOW(), NOW()),
('Vini / Enoteca',                       'vini-enoteca',                         NULL, 1, NOW(), NOW()),
('Pet / Animali',                        'pet-animali',                          NULL, 1, NOW(), NOW()),
('Assicurazioni',                        'assicurazioni',                        NULL, 1, NOW(), NOW()),
('Consulenza finanziaria',               'consulenza-finanziaria',               NULL, 1, NOW(), NOW()),
('Intermediazione del credito',          'intermediazione-del-credito',           NULL, 1, NOW(), NOW()),
('Onoranze funebri',                     'onoranze-funebri',                     NULL, 1, NOW(), NOW());
